local H = require("tests.helpers")

H.test("snapshot captures the worktree without changing the real index", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  H.write(root .. "/deleted.txt", "deleted\n")
  H.git(root, { "add", "deleted.txt" })
  H.git(root, { "commit", "-qm", "add deleted file" })
  H.write(root .. "/staged.txt", "staged\n")
  H.git(root, { "add", "staged.txt" })
  local real_index_before = H.git(root, { "write-tree" })
  H.write(root .. "/tracked.txt", "worktree\n")
  vim.fn.delete(root .. "/deleted.txt")
  H.write(root .. "/untracked.txt", "untracked\n")
  local git, err = Git.new(root)
  H.eq(nil, err)
  local tree = assert(git:snapshot())
  H.eq(real_index_before, H.git(root, { "write-tree" }))
  H.eq("worktree", H.git(root, { "show", tree .. ":tracked.txt" }))
  H.eq("untracked", H.git(root, { "show", tree .. ":untracked.txt" }))
  H.eq("staged", H.git(root, { "show", tree .. ":staged.txt" }))
  local deleted = vim.system({ "git", "show", tree .. ":deleted.txt" }, { cwd = root }):wait()
  H.truthy(deleted.code ~= 0, "deleted worktree file must be absent from snapshot")
  git:cleanup()
end)

H.test("snapshot excludes ignored untracked files", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  H.write(root .. "/.gitignore", "ignored.txt\n")
  H.write(root .. "/ignored.txt", "ignored\n")
  local real_index_before = H.git(root, { "write-tree" })
  local git = assert(Git.new(root))
  local tree = assert(git:snapshot())
  local result = vim.system({ "git", "show", tree .. ":ignored.txt" }, { cwd = root }):wait()
  H.truthy(result.code ~= 0, "ignored file must not appear in snapshot")
  H.eq("ignored.txt", H.git(root, { "show", tree .. ":.gitignore" }))
  H.eq(real_index_before, H.git(root, { "write-tree" }))
  git:cleanup()
end)

H.test("Git.new reports not_git outside a repository", function()
  local Git = require("pi.review.git")
  local git, err = Git.new(H.tmpdir())
  H.eq(nil, git)
  H.eq("not_git", err.kind)
  H.eq("discover_root", err.operation)
  H.truthy(type(err.message) == "string" and err.message ~= "")
end)

H.test("snapshot supports an unborn repository", function()
  local Git = require("pi.review.git")
  local root = H.tmpdir()
  H.git(root, { "init", "-q" })
  H.write(root .. "/first.txt", "first\n")
  local real_index_before = H.git(root, { "write-tree" })
  local git = assert(Git.new(root))
  local tree = assert(git:snapshot())
  H.eq("first", H.git(root, { "show", tree .. ":first.txt" }))
  H.eq(real_index_before, H.git(root, { "write-tree" }))
  git:cleanup()
end)

local function real_index_tree(root)
  return H.git(root, { "write-tree" })
end

local function assert_real_index(root, expected, operation)
  H.eq(expected, real_index_tree(root), operation .. " must not change the real index")
end

local function write_bytes(path, data, mode)
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  local fd = assert(vim.uv.fs_open(path, "w", mode or 420))
  assert(vim.uv.fs_write(fd, data, 0))
  assert(vim.uv.fs_close(fd))
end

H.test("changed_files, diff, and hunk_count report literal tree differences", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  local git = assert(Git.new(root))
  local first = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  H.write(root .. "/tracked.txt", "changed\n")
  H.write(root .. "/new file.txt", "new\n")
  local second = assert(git:snapshot())
  local files = assert(git:changed_files(first, second))
  H.eq({
    { path = "new file.txt", status = "A", additions = 1, deletions = 0, binary = false },
    { path = "tracked.txt", status = "M", additions = 1, deletions = 1, binary = false },
  }, files)
  assert_real_index(root, real_index_before, "changed_files")
  local patch = assert(git:diff(first, second, "tracked.txt"))
  H.truthy(patch:find("-base\n+changed\n", 1, true), "diff must contain the literal changed lines")
  assert_real_index(root, real_index_before, "diff")
  H.eq(1, assert(git:hunk_count(first, second, "tracked.txt")))
  assert_real_index(root, real_index_before, "hunk_count")
  git:cleanup()
end)

H.test("changed_files reports binary numstat fields", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  local git = assert(Git.new(root))
  local first = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  write_bytes(root .. "/binary.dat", "before\0bytes")
  local second = assert(git:snapshot())
  H.eq({
    { path = "binary.dat", status = "A", additions = nil, deletions = nil, binary = true },
  }, assert(git:changed_files(first, second)))
  assert_real_index(root, real_index_before, "binary changed_files")
  git:cleanup()
end)

H.test("entry and read_file preserve executable mode and exact bytes", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  H.write(root .. "/script.sh", "#!/bin/sh\nprintf exact\n")
  assert(vim.uv.fs_chmod(root .. "/script.sh", 493))
  local git = assert(Git.new(root))
  local tree = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  local entry = assert(git:entry(tree, "script.sh"))
  H.eq("100755", entry.mode)
  H.eq("blob", entry.type)
  H.eq("script.sh", entry.path)
  H.truthy(entry.oid:match("^[0-9a-f]+$") and #entry.oid == 40)
  assert_real_index(root, real_index_before, "entry")
  local file = assert(git:read_file(tree, "script.sh"))
  H.eq("#!/bin/sh\nprintf exact\n", file.data)
  H.eq("100755", file.mode)
  H.eq(entry.oid, file.oid)
  assert_real_index(root, real_index_before, "read_file")
  git:cleanup()
end)

H.test("copy_path changes only the selected path in a tree", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  H.write(root .. "/other.txt", "other-base\n")
  local git = assert(Git.new(root))
  local base = assert(git:snapshot())
  H.write(root .. "/tracked.txt", "source\n")
  H.write(root .. "/other.txt", "other-source\n")
  local source = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  local copied = assert(git:copy_path(base, source, "tracked.txt"))
  H.eq("source", H.git(root, { "show", copied .. ":tracked.txt" }))
  H.eq("other-base", H.git(root, { "show", copied .. ":other.txt" }))
  assert_real_index(root, real_index_before, "copy_path")
  git:cleanup()
end)

H.test("update_path removal changes only the selected path", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  H.write(root .. "/keep.txt", "keep\n")
  H.write(root .. "/remove.txt", "remove\n")
  local git = assert(Git.new(root))
  local base = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  local updated = assert(git:update_path(base, "remove.txt", nil))
  H.eq("keep", H.git(root, { "show", updated .. ":keep.txt" }))
  H.eq("keep.txt\ntracked.txt", H.git(root, { "ls-tree", "-r", "--name-only", updated }))
  assert_real_index(root, real_index_before, "update_path removal")
  git:cleanup()
end)

H.test("write_blob and update_path preserve literal partial content", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  local git = assert(Git.new(root))
  local base = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  local oid = assert(git:write_blob("partial without newline"))
  H.eq("partial without newline", H.git(root, { "cat-file", "blob", oid }))
  assert_real_index(root, real_index_before, "write_blob")
  local updated = assert(git:update_path(base, "tracked.txt", {
    mode = "100644",
    type = "blob",
    oid = oid,
    path = "tracked.txt",
  }))
  H.eq("partial without newline", H.git(root, { "show", updated .. ":tracked.txt" }))
  assert_real_index(root, real_index_before, "update_path addition")
  git:cleanup()
end)

H.test("restore_path restores bytes and mode and removes a path absent from the tree", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  H.write(root .. "/script.sh", "#!/bin/sh\nprintf restored\n")
  assert(vim.uv.fs_chmod(root .. "/script.sh", 493))
  local git = assert(Git.new(root))
  local accepted = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  H.write(root .. "/script.sh", "changed\n")
  assert(vim.uv.fs_chmod(root .. "/script.sh", 420))
  H.write(root .. "/new.txt", "remove me\n")
  H.eq(true, assert(git:restore_path(accepted, "script.sh")))
  H.eq("#!/bin/sh\nprintf restored\n", H.read(root .. "/script.sh"))
  H.eq(493, bit.band(assert(vim.uv.fs_stat(root .. "/script.sh")).mode, 511))
  assert_real_index(root, real_index_before, "restore_path regular file")
  local restored_again = git:restore_path(accepted, "new.txt")
  H.eq(true, restored_again)
  H.eq(nil, vim.uv.fs_lstat(root .. "/new.txt"))
  assert_real_index(root, real_index_before, "restore_path absent file")
  local absent_again = git:restore_path(accepted, "new.txt")
  H.eq(true, absent_again)
  assert_real_index(root, real_index_before, "restore_path already-absent file")
  git:cleanup()
end)

H.test("restore_path recreates a symbolic link from exact blob bytes", function()
  local Git = require("pi.review.git")
  local root = H.repo()
  assert(vim.uv.fs_symlink("tracked.txt", root .. "/link"))
  local git = assert(Git.new(root))
  local accepted = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  assert(vim.uv.fs_unlink(root .. "/link"))
  H.write(root .. "/link", "ordinary file\n")
  H.eq(true, assert(git:restore_path(accepted, "link")))
  H.eq("link", assert(vim.uv.fs_lstat(root .. "/link")).type)
  H.eq("tracked.txt", assert(vim.uv.fs_readlink(root .. "/link")))
  assert_real_index(root, real_index_before, "restore_path symlink")
  git:cleanup()
end)

H.test("restore_path checks out a Gitlink only in a clean initialized submodule", function()
  local Git = require("pi.review.git")
  local child = H.repo()
  local accepted_oid = H.git(child, { "rev-parse", "HEAD" })
  local root = H.repo()
  H.git(root, { "-c", "protocol.file.allow=always", "submodule", "add", "-q", child, "module" })
  H.git(root, { "commit", "-qam", "add submodule" })
  local git = assert(Git.new(root))
  local accepted = assert(git:snapshot())
  H.write(child .. "/tracked.txt", "new child commit\n")
  H.git(child, { "commit", "-qam", "second" })
  local current_oid = H.git(child, { "rev-parse", "HEAD" })
  H.git(root .. "/module", { "fetch", "-q", "origin" })
  H.git(root .. "/module", { "checkout", "-q", "--detach", current_oid })
  H.git(root, { "add", "module" })
  local real_index_before = real_index_tree(root)
  H.eq(true, assert(git:restore_path(accepted, "module")))
  H.eq(accepted_oid, H.git(root .. "/module", { "rev-parse", "HEAD" }))
  assert_real_index(root, real_index_before, "restore_path Gitlink")

  H.write(root .. "/module/tracked.txt", "dirty\n")
  local ok, err = git:restore_path(assert(git:snapshot()), "module")
  H.eq(nil, ok)
  H.eq("git", err.kind)
  H.truthy(err.message:find("clean", 1, true))
  H.eq("dirty\n", H.read(root .. "/module/tracked.txt"))
  assert_real_index(root, real_index_before, "refused dirty Gitlink restore")
  git:cleanup()
end)

H.test("restore_path removes only a clean initialized submodule absent from the tree", function()
  local Git = require("pi.review.git")
  local child = H.repo()
  local root = H.repo()
  local git = assert(Git.new(root))
  local without_submodule = assert(git:snapshot())
  H.git(root, { "-c", "protocol.file.allow=always", "submodule", "add", "-q", child, "module" })
  local real_index_before = real_index_tree(root)
  H.eq(true, assert(git:restore_path(without_submodule, "module")))
  H.eq(nil, vim.uv.fs_lstat(root .. "/module"))
  assert_real_index(root, real_index_before, "restore_path absent Gitlink")
  git:cleanup()
end)

H.test("restore_path rejects a sibling-prefix escape without disk or index mutation", function()
  local Git = require("pi.review.git")
  local parent = H.tmpdir()
  local root = parent .. "/repository"
  local sibling = parent .. "/repository-evil"
  vim.fn.mkdir(root, "p")
  vim.fn.mkdir(sibling, "p")
  H.git(root, { "init", "-q" })
  H.git(root, { "config", "user.name", "pi.nvim tests" })
  H.git(root, { "config", "user.email", "pi.nvim@example.invalid" })
  H.write(root .. "/tracked.txt", "base\n")
  H.git(root, { "add", "tracked.txt" })
  H.git(root, { "commit", "-qm", "base" })
  H.write(sibling .. "/file", "untouched\n")
  local git = assert(Git.new(root))
  local tree = assert(git:snapshot())
  local real_index_before = real_index_tree(root)
  local ok, err = git:restore_path(tree, "../repository-evil/file")
  H.eq(nil, ok)
  H.eq("git", err.kind)
  H.eq("untouched\n", H.read(sibling .. "/file"))
  assert_real_index(root, real_index_before, "rejected path")
  git:cleanup()
end)
