local H = require("tests.helpers")

H.test("resolve_cwd normalizes fixed and dynamic cwd values", function()
  local config = require("pi.config")
  local project = require("pi.project")
  local root = H.tmpdir()
  config.setup({ project = { cwd = root .. "/." } })
  H.eq(root, project.resolve_cwd())
  config.setup({ project = { cwd = nil } })
  local previous = vim.fn.getcwd()
  vim.cmd.lcd(vim.fn.fnameescape(root))
  H.eq(root, project.resolve_cwd())
  vim.cmd.lcd(vim.fn.fnameescape(previous))
end)

H.test("is_within rejects sibling prefix collisions", function()
  local project = require("pi.project")
  H.eq(true, project.is_within("/tmp/app", "/tmp/app/lua/a.lua"))
  H.eq(true, project.is_within("/tmp/app", "/tmp/app"))
  H.eq(false, project.is_within("/tmp/app", "/tmp/application/a.lua"))
end)

H.test("is_within treats filesystem root as a boundary", function()
  local project = require("pi.project")
  H.eq(true, project.is_within("/", "/tmp/file"))
end)

H.test("save_modified writes only normal buffers inside the boundary", function()
  local project = require("pi.project")
  local root = H.tmpdir()
  local outside = H.tmpdir()
  H.write(root .. "/inside.txt", "disk\n")
  H.write(outside .. "/outside.txt", "outside-disk\n")
  local inside_buf = vim.fn.bufadd(root .. "/inside.txt")
  local outside_buf = vim.fn.bufadd(outside .. "/outside.txt")
  vim.fn.bufload(inside_buf)
  vim.fn.bufload(outside_buf)
  vim.api.nvim_buf_set_lines(inside_buf, 0, -1, false, { "inside-buffer" })
  vim.api.nvim_buf_set_lines(outside_buf, 0, -1, false, { "outside-buffer" })
  local ok, err = project.save_modified(root)
  H.eq(true, ok)
  H.eq(nil, err)
  H.eq("inside-buffer\n", H.read(root .. "/inside.txt"))
  H.eq("outside-disk\n", H.read(outside .. "/outside.txt"))
  H.eq(true, vim.bo[outside_buf].modified)
end)

H.test("save_modified returns a path-bearing error and stops after a save failure", function()
  local project = require("pi.project")
  local root = H.tmpdir()
  local readonly_path = root .. "/readonly.txt"
  local later_path = root .. "/later.txt"
  H.write(readonly_path, "readonly-disk\n")
  H.write(later_path, "later-disk\n")
  local readonly_buf = vim.fn.bufadd(readonly_path)
  local later_buf = vim.fn.bufadd(later_path)
  vim.fn.bufload(readonly_buf)
  vim.fn.bufload(later_buf)
  vim.api.nvim_buf_set_lines(readonly_buf, 0, -1, false, { "readonly-buffer" })
  vim.api.nvim_buf_set_lines(later_buf, 0, -1, false, { "later-buffer" })
  vim.bo[readonly_buf].readonly = true

  local ok, err = project.save_modified(root)

  pcall(vim.api.nvim_buf_call, readonly_buf, function()
    vim.bo.readonly = false
  end)
  H.eq(false, ok)
  H.truthy(err:find(readonly_path, 1, true))
  H.eq("readonly-disk\n", H.read(readonly_path))
  H.eq("later-disk\n", H.read(later_path))
  H.eq(true, vim.bo[later_buf].modified)
end)
